INSERT INTO projects VALUES
(1,"WordLinks","some url","cpp","https://github.com/bdajeje/WordLinks"),
(2,"Remove Trailing Lines","some url","cpp","https://github.com/bdajeje/remove-trailing-lines"),
(3,"Open Weather Map","some url","cpp","https://github.com/bdajeje/OpenWeatherMap"),
(4,"Graphite Proxy","some url","cpp","https://github.com/bdajeje/graphite-proxy"),
(5,"Soundcloud Sync","some url","ruby","https://github.com/bdajeje/SoundCloudSync"),
(6,"Geomart","some url","cpp","https://github.com/bdajeje/Geomart"),
(7,"Langton Ant","some url","cpp","https://github.com/bdajeje/LangtonAnt"),
(8,"Graph Chromatic","some url","cpp","https://github.com/bdajeje/GraphChromatic"),
(9,"Maximize Image","some url","js","https://github.com/bdajeje/JS-MaximizeImage"),
(10,"Obelisk","some url","js","https://github.com/bdajeje/Obelisk"),
(11,"QtNotes","some url","cpp","https://github.com/bdajeje/QTNotes"),
(12,"QtAlarm","some url","cpp","https://github.com/bdajeje/QtAlarm"),
(13,"Prime Numbers","some url","cpp","https://github.com/bdajeje/PrimeNumbers"),
(14,"My Favorites","some url","cpp","https://github.com/bdajeje/MyFavorites");

INSERT INTO project_texts (projectId, language, text) VALUES
(1, 'en', 'Reads texts and builds links between words to extract their relationships. Basically builds a graph of words.<br/>After a text has been analyzed we can ask for word/entity top relations.<br/><br/>Command line project.'),
(1, 'fr', 'Projet en ligne de commande qui lit et analyse un texte afin d\'établire des relations entre mots.<br/>Construit un graph de mots pour ensuite connaître leurs relations. Après analyse on peut facilement demander les meilleurs relations pour chaque mot.'),
(2, 'en', 'Removes extra blank lines at the end of files. Usefull to clean your source files.'),
(2, 'fr', 'Supprime les lignes vides à la fin de fichiers. Utile pour nettoyer vos fichiers de code.'),
(3, 'en', 'Gives weather information about a city. Cache results to prevent querying API too much.'),
(3, 'fr', 'Donne la météo d\'une ville. Sauvegarde les résultats en cache pour éviter de questionner l\'API trop souvent.'),
(4, 'en', 'english description'),
(4, 'fr', 'description francaise'),
(5, 'en', 'english description'),
(5, 'fr', 'description francaise'),
(6, 'en', 'english description'),
(6, 'fr', 'description francaise'),
(7, 'en', 'english description'),
(7, 'fr', 'description francaise'),
(8, 'en', 'english description'),
(8, 'fr', 'description francaise'),
(9, 'en', 'english description'),
(9, 'fr', 'description francaise'),
(10, 'en', 'english description'),
(10, 'fr', 'description francaise'),
(11, 'en', 'english description'),
(11, 'fr', 'description francaise'),
(12, 'en', 'english description'),
(12, 'fr', 'description francaise'),
(13, 'en', 'english description'),
(13, 'fr', 'description francaise'),
(14, 'en', 'english description'),
(14, 'fr', 'description francaise');
